
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Oct 16 18:07:34 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTH = 31;
  public static final int LETH = 33;
  public static final int CONST = 7;
  public static final int CHAR = 20;
  public static final int NAMESPACE = 6;
  public static final int NOTEQUAL = 44;
  public static final int CONTINUE = 45;
  public static final int LPAREN = 15;
  public static final int SEMI = 8;
  public static final int FOR = 22;
  public static final int MINUS = 29;
  public static final int STATIC = 23;
  public static final int RPAREN = 16;
  public static final int AND = 32;
  public static final int EQUALTO = 38;
  public static final int OR = 42;
  public static final int BOOL = 19;
  public static final int COMMA = 10;
  public static final int INC = 37;
  public static final int DIV = 28;
  public static final int PLUS = 21;
  public static final int IF = 27;
  public static final int DOT = 46;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int EQUAL = 9;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int MOD = 35;
  public static final int NUMBER = 17;
  public static final int BREAK = 3;
  public static final int GTH = 30;
  public static final int IDENT = 18;
  public static final int VOID = 14;
  public static final int COLON = 13;
  public static final int LBRACE = 4;
  public static final int ELSE = 26;
  public static final int LSQUARE = 11;
  public static final int READ = 47;
  public static final int RSQUARE = 12;
  public static final int NOTEQUALTO = 40;
  public static final int RBRACE = 5;
  public static final int PROG = 2;
  public static final int ARR = 25;
  public static final int DEC = 43;
  public static final int PRINT = 39;
  public static final int GETH = 34;
}

